// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzue5MMgTkByXfyEXtl2JQVEb2Cof-91A',
    appId: '1:160158651929:web:329ad16b5177b1066cfc88',
    messagingSenderId: '160158651929',
    projectId: 'el-moza3',
    authDomain: 'el-moza3.firebaseapp.com',
    storageBucket: 'el-moza3.firebasestorage.app',
    measurementId: 'G-0EVF1QP5RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzZktWSA38In5-H7Us0IJxe1vTYxaXkI',
    appId: '1:160158651929:android:90e06770ead0aaff6cfc88',
    messagingSenderId: '160158651929',
    projectId: 'el-moza3',
    storageBucket: 'el-moza3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKRljWQSz3NFsFImmdfAY0JTFKOY3zBs',
    appId: '1:160158651929:ios:c59b209d81ea96ec6cfc88',
    messagingSenderId: '160158651929',
    projectId: 'el-moza3',
    storageBucket: 'el-moza3.firebasestorage.app',
    iosBundleId: 'com.example.elMoza3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKRljWQSz3NFsFImmdfAY0JTFKOY3zBs',
    appId: '1:160158651929:ios:c59b209d81ea96ec6cfc88',
    messagingSenderId: '160158651929',
    projectId: 'el-moza3',
    storageBucket: 'el-moza3.firebasestorage.app',
    iosBundleId: 'com.example.elMoza3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzue5MMgTkByXfyEXtl2JQVEb2Cof-91A',
    appId: '1:160158651929:web:6b231b2388f0f02e6cfc88',
    messagingSenderId: '160158651929',
    projectId: 'el-moza3',
    authDomain: 'el-moza3.firebaseapp.com',
    storageBucket: 'el-moza3.firebasestorage.app',
    measurementId: 'G-7TYWK1V780',
  );
}
